services:
  web:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - '/home/selmeg/Desktop/nginx.conf:/etc/nginx/conf.d/default.conf'
      - '.:/var/www/html'

  php-fpm:
    build: ./Docker
    volumes:
      - .:/var/www/html


  postgres:
    image: postgres:13
    container_name: postgres_db
    ports:
      - 54323:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
