services:
  web:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - './Docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
      - '.:/var/www/html'

  php-fpm:
    build: ./Docker/php
    volumes:
      - .:/var/www/html
      - ./Docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini


  postgres:
    image: postgres:13
    container_name: postgres_db
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    ports:
      - 54323:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
